insert into shift_type_skill_requirement (shift_id, skill_id) values (1, 1)
insert into shift_type_skill_requirement (shift_id, skill_id) values (1, 2)
insert into shift_type_skill_requirement (shift_id, skill_id) values (1, 3)
insert into shift_type_skill_requirement (shift_id, skill_id) values (2, 1)
insert into shift_type_skill_requirement (shift_id, skill_id) values (3, 1)
